#!/usr/bin/env node
const chalk = require('chalk');
const gitlabCiValidate = require('../src/index');

const cmd = process.argv[2];

if (!cmd || cmd === '-h' || cmd === '--help') {
  console.log(`
  Usage
    $ gitlab-ci-validate <file-path>
  Help
    $ gitlab-ci-validate -h --help
  `);
  process.exit(0);
}

gitlabCiValidate(cmd).then((data) => {
  if (data.status === 'valid') {
    console.log(chalk.green(`${cmd} is valid`));
  } else {
    console.log(chalk.red(`${cmd} is invalid:`));
    data.errors.forEach((err) => {
      console.log(chalk.red(`- ${err}`));
    });
  }
}).catch((err) => {
  console.error(chalk.red(err));
});
