#!/usr/bin/env node
const fs = require('fs');
const sade = require('sade');
const kleur = require('kleur');
const gitlabCiPkg = require('../package.json');
const gitlabCiValidate = require('../src/index');

const prog = sade(gitlabCiPkg.name);

prog.version(gitlabCiPkg.version);

prog
  .command('validate [file]', '', { default: true })
  .describe('Manage set of tracked repositories')
  .option(
    '--host, -H',
    'Change the gitlab host (default to https://gitlab.com)'
  )
  .option(
    '--private_token, -P',
    'Authenticate to gitlab api using a private token'
  )
  .action((file, opts) => {
    // Default file is .gitlab-ci.yml
    if (!file) {
      file = '.gitlab-ci.yml';
    }

    if (!fs.existsSync(file)) {
      console.log(kleur.red(`ERROR: ${file} does not exists!`));
      process.exit(1);
    }

    gitlabCiValidate(file, {
      host: opts.host,
      private_token: opts.private_token,
    })
      .then(data => {
        if (data.status === 'valid') {
          console.log(kleur.green(`${file} is valid`));
          process.exit(0);
        } else if (data.error){
          console.log(kleur.red(`${data.error} - ${data.error_description}`));
        } else if (data.message){
          console.log(kleur.yellow(`${data.message}`));
        } else {
          console.log(kleur.red(`${file} is invalid:`));
          data.errors.forEach(err => {
            console.log(kleur.red(`  - ${err}`));
          });
          process.exit(1);
        }
      })
      .catch(err => {
        console.error(kleur.red(err));
        process.exit(1);
      });
  });

prog.parse(process.argv);
