#!/usr/bin/env node
const fs = require('fs');
const kleur = require('kleur');
const gitlabCiValidate = require('../src/index');

function showHelp() {
  console.log(`
  Usage
    $ gitlab-ci-validate <file-path>
  Help
    $ gitlab-ci-validate -h --help
  `);
  process.exit(0);
}

let cmd = process.argv[2];

// Default file is .gitlab-ci.yml
if (!cmd) {
  cmd = '.gitlab-ci.yml';
}

if (cmd === '-h' || cmd === '--help') {
  showHelp();
}

if (!fs.existsSync(cmd)) {
  console.log(chalk.red(`ERROR: ${cmd} does not exists!`));
  showHelp();
}

gitlabCiValidate(cmd)
  .then(data => {
    if (data.status === 'valid') {
      console.log(kleur.green(`${cmd} is valid`));
      process.exit(0);
    } else {
      console.log(kleur.red(`${cmd} is invalid:`));
      data.errors.forEach(err => {
        console.log(kleur.red(`  - ${err}`));
      });
      process.exit(1);
    }
  })
  .catch(err => {
    console.error(kleur.red(err));
    process.exit(1);
  });
